site_name: SuperSQL
site_url: https://www.github.com/rayattack/supersql
site_description: Python to SQL engine
site_author: Raymond Ortserga

repo_name: rayattack/supersql
repo_url: https://www.github.com/rayattack/supersql

theme:
  name: 'material'
  palette:
    primary: black
  include_search_page: false
  features:
    - navigation.tabs
    - navigation.instant
  logo: images/logo.png

plugins:
  - search

nav:
  - Welcome To Supersql: index.md
  - Installation & Setup:
      - Getting Started: installation.md
      - Vendor Dependencies: vendor-dependencies.md
      - Connecting to Databases: connecting.md
  - Core Concepts:
      - Schema Definition: schema.md
      - Data Types: datatypes.md
      - Query Builder: query.md
      - Results & Iteration: results.md
      - Reflection & Inspection: reflection.md
  - Examples:
    - Overview: examples.md
    - BETWEEN: examples/between.md
    - CAST: examples/cast.md
    - CONCAT Alias: examples/concat-alias.md
    - Connection: examples/connecting.md
    - Cursor: examples/cursor.md
    - DELETE: examples/delete.md
    - ENUM: examples/enum.md
    - Excepts: examples/excepts.md
    - Fetch: examples/fetch.md
    - Function: examples/function.md
    - GROUP BY: examples/group-by.md
    - IN Select: examples/in-select.md
    - INSERT: examples/insert.md
    - JOIN: examples/join.md
    - NULL: examples/null.md
    - QUERY: examples/query.md
    - Results: examples/results.md
    - SELECT: examples/select.md
    - Unary: examples/unary.md
    - UNION: examples/union.md
    - UPDATE: examples/update.md
    - UPSERT: examples/upsert.md
    - WHERE: examples/where.md
    - WITH RECURSIVE: examples/with-recursive.md
    - WITH: examples/with.md
    - Without Query Object: examples/without-query.md
  - Advanced Topics:
    - Joins: joins.md
    - Filtering: filter.md
    - DDL Operations: ddl/create.md
    - DQL Operations: dql/select.md
    - Commits: commit.md

extra_css:
  - 'custom.css'

markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.codehilite:
      guess_lang: false
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
